# Setup
title:               Ram Shankar Yadav's
tagline:             'blog'
description:         <img src="/images/run-svgrepo-com.svg" style="width:80px;height:80px;">  Ram Shankar Yadav's blog!
url:                 https://ram.run
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ram Shankar Yadav
  url:               https://twitter.com/ramshankaryadav
  email:             ramshankaryadav@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
